export const staticFleets = [
  {
    category: "ECONOMY",
    displayName: "Economy",
    vehicles: ["Toyota Corolla Hybrid", "Or Similar"],
    passengers: 4,
    luggage: 4,
    imageUrl: "/Econamy.webp",
    pricing: { perKm: 1.5, hourly: 30, airport: 35 },
    hasChargingPort: false,
  },
  {
    category: "BUSINESS_SEDAN",
    displayName: "Business Sedan",
    vehicles: ["Mercedes E Class or superior"],
    passengers: 4,
    luggage: 4,
    imageUrl: "/Mercedes-S-Class-cutout.webp",
    pricing: { perKm: 1.7, hourly: 40, airport: 50 },
    hasChargingPort: true,
    priceIncrease: 0.08,
  },
  {
    category: "ECONOMY_VAN",
    displayName: "Economy Van",
    vehicles: ["Mercedes Vito", "Or Similar"],
    passengers: 8,
    luggage: 8,
    imageUrl: "/Economy Van.png",
    pricing: { perKm: 2.0, hourly: 50, airport: 50 },
    hasChargingPort: false,
  },
  {
    category: "BUSINESS_VAN",
    displayName: "First Class Van",
    vehicles: ["Mercedes V Class"],
    passengers: 7,
    luggage: 7,
    imageUrl: "/First Class Van.png",
    pricing: { perKm: 2.5, hourly: 60, airport: 60 },
    hasChargingPort: true,
    priceIncrease: 0.10,
  },
  {
    category: "MINIBUS_12",
    displayName: "Minibus 12 (or two vans)",
    vehicles: ["Mercedes Sprinter or similar"],
    passengers: 12,
    luggage: 12,
    imageUrl: "/Minibus 12.png",
    pricing: { perKm: 3.5, hourly: 80, airport: 85 },
    hasChargingPort: true,
  },
  {
    category: "MINIBUS_16",
    displayName: "Minibus 16 (or two vans)",
    vehicles: ["Mercedes Sprinter or similar"],
    passengers: 16,
    luggage: 16,
    imageUrl: "/Minibus 16.png",
    pricing: { perKm: 4.0, hourly: 100, airport: 100 },
    hasChargingPort: true,
  },
];